import React from "react";
import "./bodystyle.css";


function Body() {
    return (
        <div className="paragraph">

        <div className="buttons">
            <button style={{backgroundColor:"red"}}></button>
            <button style={{backgroundColor:"gray"}}></button>
            <button style={{backgroundColor:"green"}}></button>
        </div>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet enim. Sagittis id consectetur purus ut faucibus pulvinar. Eget lorem dolor sed viverra ipsum nunc. Orci porta non pulvinar neque laoreet suspendisse interdum. Massa sed elementum tempus egestas sed sed. Fringilla urna porttitor rhoncus dolor. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Enim nunc faucibus a pellentesque sit. Consectetur libero id faucibus nisl tincidunt eget. Nibh cras pulvinar mattis nunc sed. Augue ut lectus arcu bibendum at. Netus et malesuada fames ac turpis egestas maecenas. Neque ornare aenean euismod elementum nisi quis eleifend quam adipiscing. Feugiat vivamus at augue eget arcu dictum varius.

                In dictum non consectetur a erat nam at lectus urna. Pretium viverra suspendisse potenti nullam ac tortor vitae. A scelerisque purus semper eget duis at tellus at. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Tellus pellentesque eu tincidunt tortor. Sed nisi lacus sed viverra tellus. Condimentum vitae sapien pellentesque habitant morbi tristique senectus. Scelerisque varius morbi enim nunc faucibus a pellentesque sit amet. Amet nulla facilisi morbi tempus iaculis urna id. Facilisis volutpat est velit egestas dui id ornare arcu. Purus non enim praesent elementum facilisis.

                Scelerisque in dictum non consectetur a erat nam at. Amet risus nullam eget felis eget nunc lobortis. Sit amet tellus cras adipiscing enim eu turpis. Interdum varius sit amet mattis vulputate enim nulla. Tortor posuere ac ut consequat semper viverra. Risus feugiat in ante metus dictum at. Sed blandit libero volutpat sed cras ornare arcu dui vivamus. Tortor dignissim convallis aenean et tortor. Senectus et netus et malesuada fames ac turpis egestas integer. Non enim praesent elementum facilisis leo vel. Vestibulum morbi blandit cursus risus.

                
                Augue mauris augue neque gravida in fermentum et sollicitudin. Sagittis id consectetur purus ut faucibus pulvinar elementum integer. Duis tristique sollicitudin nibh sit. Nam at lectus urna duis convallis convallis tellus id interdum. Non quam lacus suspendisse faucibus interdum. Et tortor consequat id porta nibh venenatis cras. Semper quis lectus nulla at volutpat. Cursus in hac habitasse platea dictumst. Euismod nisi porta lorem mollis aliquam ut. At urna condimentum mattis pellentesque id. Eu volutpat odio facilisis mauris sit amet massa vitae. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. Quam quisque id diam vel. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Tempor orci eu lobortis elementum nibh tellus molestie. Viverra suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Eu consequat ac felis donec et odio. Ornare arcu dui vivamus arcu. In massa tempor nec feugiat nisl pretium fusce id velit. A iaculis at erat pellentesque adipiscing.

                Arcu felis bibendum ut tristique et egestas quis ipsum suspendisse. Eu tincidunt tortor aliquam nulla facilisi cras. Senectus et netus et malesuada fames ac turpis egestas. Pulvinar mattis nunc sed blandit libero volutpat. Nulla facilisi morbi tempus iaculis urna. Pharetra pharetra massa massa ultricies mi quis hendrerit. Aliquet risus feugiat in ante metus. Elit ut aliquam purus sit amet luctus venenatis lectus. Tincidunt arcu non sodales neque sodales ut. Tristique et egestas quis ipsum suspendisse. Nibh praesent tristique magna sit amet purus. Volutpat maecenas volutpat blandit aliquam etiam erat. Sit amet facilisis magna etiam tempor. Neque viverra justo nec ultrices dui sapien eget. Odio eu feugiat pretium nibh ipsum consequat nisl vel. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla. Praesent tristique magna sit amet. Facilisis gravida neque convallis a. Fermentum odio eu feugiat pretium.

                Non sodales neque sodales ut. Tincidunt tortor aliquam nulla facilisi cras fermentum odio. Vulputate ut pharetra sit amet aliquam id diam maecenas ultricies. Ut sem nulla pharetra diam. Egestas dui id ornare arcu odio ut sem. Velit scelerisque in dictum non consectetur a erat nam. Risus ultricies tristique nulla aliquet. A diam sollicitudin tempor id eu nisl nunc mi. Ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. Arcu non odio euismod lacinia at quis risus. Egestas integer eget aliquet nibh praesent tristique magna sit amet. Turpis egestas maecenas pharetra convallis posuere morbi. Volutpat ac tincidunt vitae semper.

                Ultrices in iaculis nunc sed augue lacus. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel. Felis eget velit aliquet sagittis id consectetur purus. Aliquam ut porttitor leo a. Integer enim neque volutpat ac tincidunt vitae semper quis lectus. Augue eget arcu dictum varius duis at consectetur. Sagittis aliquam malesuada bibendum arcu. Tortor pretium viverra suspendisse potenti nullam. Mauris pharetra et ultrices neque ornare aenean euismod. Imperdiet sed euismod nisi porta lorem mollis aliquam ut. Eu consequat ac felis donec. Nibh praesent tristique magna sit. Semper risus in hendrerit gravida. Arcu non sodales neque sodales ut etiam sit amet.

                At risus viverra adipiscing at in tellus integer. Semper viverra nam libero justo laoreet. Tellus integer feugiat scelerisque varius morbi enim nunc. Faucibus purus in massa tempor nec feugiat nisl. Nunc vel risus commodo viverra maecenas accumsan. Pulvinar etiam non quam lacus suspendisse faucibus interdum. Ut sem nulla pharetra diam. Fringilla est ullamcorper eget nulla facilisi etiam dignissim. Et malesuada fames ac turpis egestas maecenas pharetra convallis posuere. Placerat in egestas erat imperdiet sed euismod nisi porta. Eget arcu dictum varius duis at consectetur lorem donec.

                Morbi tincidunt ornare massa eget egestas purus viverra. Vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Mauris ultrices eros in cursus turpis. In mollis nunc sed id semper risus in hendrerit gravida. Dolor purus non enim praesent elementum facilisis leo vel. Erat imperdiet sed euismod nisi porta lorem mollis aliquam ut. Sed id semper risus in hendrerit gravida. Mattis aliquam faucibus purus in massa tempor. Pretium quam vulputate dignissim suspendisse in est ante in nibh. Nisi scelerisque eu ultrices vitae auctor eu. Tristique senectus et netus et malesuada fames. Convallis convallis tellus id interdum velit laoreet. Eu consequat ac felis donec et odio. Neque ornare aenean euismod elementum nisi. Ut tortor pretium viverra suspendisse potenti nullam ac. Id interdum velit laoreet id donec ultrices. Morbi blandit cursus risus at ultrices mi. Commodo odio aenean sed adipiscing diam donec adipiscing tristique.

                Senectus et netus et malesuada fames ac turpis. Leo a diam sollicitudin tempor id. Vitae nunc sed velit dignissim sodales ut. Magna sit amet purus gravida quis. Dolor sit amet consectetur adipiscing elit pellentesque. Cursus risus at ultrices mi. A scelerisque purus semper eget duis at tellus at urna. Facilisis leo vel fringilla est ullamcorper eget nulla. Nec ultrices dui sapien eget. Molestie at elementum eu facilisis sed odio morbi quis commodo. Elit scelerisque mauris pellentesque pulvinar. Egestas congue quisque egestas diam. Enim sed faucibus turpis in eu mi bibendum neque egestas.

                Pretium nibh ipsum consequat nisl vel pretium. Sit amet massa vitae tortor condimentum lacinia quis vel eros. Egestas dui id ornare arcu odio ut sem. Pharetra magna ac placerat vestibulum lectus mauris ultrices. Eget gravida cum sociis natoque penatibus et magnis dis. Nulla facilisi nullam vehicula ipsum a arcu cursus. Proin nibh nisl condimentum id venenatis a condimentum vitae. A erat nam at lectus urna. Sed egestas egestas fringilla phasellus. Eget gravida cum sociis natoque penatibus et. Enim nunc faucibus a pellentesque sit amet porttitor eget. Natoque penatibus et magnis dis parturient montes.

                Urna id volutpat lacus laoreet. Blandit turpis cursus in hac habitasse. Elementum integer enim neque volutpat ac tincidunt vitae semper quis. Duis at tellus at urna condimentum mattis pellentesque id nibh. Dolor sed viverra ipsum nunc aliquet. Mi proin sed libero enim. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc. Eu scelerisque felis imperdiet proin fermentum leo. Diam maecenas sed enim ut sem viverra. Vitae et leo duis ut. Lobortis elementum nibh tellus molestie nunc non blandit. In metus vulputate eu scelerisque felis imperdiet proin fermentum leo. Faucibus turpis in eu mi. Elit ullamcorper dignissim cras tincidunt. Amet cursus sit amet dictum sit. Bibendum at varius vel pharetra vel turpis nunc.

                Tempor orci dapibus ultrices in. Risus viverra adipiscing at in tellus integer feugiat scelerisque varius. Egestas diam in arcu cursus euismod quis viverra nibh cras. Ac turpis egestas integer eget aliquet. Eget dolor morbi non arcu risus quis varius. Tempor orci eu lobortis elementum nibh tellus molestie nunc non. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Scelerisque in dictum non consectetur a erat nam. In nulla posuere sollicitudin aliquam. In ante metus dictum at tempor commodo ullamcorper a lacus. Mattis nunc sed blandit libero volutpat. Luctus accumsan tortor posuere ac ut consequat semper viverra. Maecenas volutpat blandit aliquam etiam erat velit scelerisque.

                Non quam lacus suspendisse faucibus. Sed libero enim sed faucibus turpis in eu. Eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Ut pharetra sit amet aliquam. Condimentum vitae sapien pellentesque habitant morbi tristique. Pretium nibh ipsum consequat nisl. Nullam vehicula ipsum a arcu. Sed turpis tincidunt id aliquet risus feugiat. Felis eget velit aliquet sagittis id consectetur purus. Egestas pretium aenean pharetra magna ac. Nec dui nunc mattis enim ut. Nisi porta lorem mollis aliquam ut porttitor. Morbi tristique senectus et netus et. Nisl nisi scelerisque eu ultrices vitae auctor eu.

                Vel pretium lectus quam id leo in vitae turpis massa. Nunc mattis enim ut tellus elementum sagittis vitae. Cras sed felis eget velit aliquet sagittis id consectetur purus. Velit laoreet id donec ultrices tincidunt. Adipiscing vitae proin sagittis nisl rhoncus mattis. Suspendisse ultrices gravida dictum fusce ut placerat orci nulla. Ultricies leo integer malesuada nunc vel risus commodo viverra maecenas. Morbi leo urna molestie at elementum eu facilisis sed. Est pellentesque elit ullamcorper dignissim. Tellus cras adipiscing enim eu turpis egestas pretium aenean pharetra. Aliquam sem fringilla ut morbi tincidunt augue. Sagittis purus sit amet volutpat. Est ultricies integer quis auctor elit sed vulputate mi sit. Pretium vulputate sapien nec sagittis aliquam malesuada bibendum arcu. Nullam ac tortor vitae purus faucibus ornare. Eget lorem dolor sed viverra ipsum nunc aliquet bibendum enim. Sit amet massa vitae tortor condimentum. A cras semper auctor neque. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Adipiscing elit pellentesque habitant morbi tristique senectus.

                Quisque sagittis purus sit amet volutpat consequat mauris nunc. Orci dapibus ultrices in iaculis nunc sed augue lacus viverra. Enim praesent elementum facilisis leo vel fringilla. Nunc mattis enim ut tellus elementum. Nunc mattis enim ut tellus elementum sagittis vitae. Facilisi nullam vehicula ipsum a arcu cursus vitae. Euismod nisi porta lorem mollis aliquam ut porttitor leo a. Proin nibh nisl condimentum id. Nunc sed id semper risus in hendrerit gravida rutrum quisque. Dapibus ultrices in iaculis nunc sed. Lorem ipsum dolor sit amet consectetur adipiscing elit. Consequat ac felis donec et odio pellentesque. Libero justo laoreet sit amet cursus sit. Molestie nunc non blandit massa enim nec. Fames ac turpis egestas maecenas pharetra convallis. Turpis massa tincidunt dui ut ornare lectus. Nibh venenatis cras sed felis eget velit aliquet sagittis id.

                Bibendum at varius vel pharetra vel turpis nunc eget. Nec tincidunt praesent semper feugiat nibh sed pulvinar proin gravida. Pellentesque adipiscing commodo elit at imperdiet dui accumsan. Porta nibh venenatis cras sed felis. Cursus vitae congue mauris rhoncus aenean. Praesent semper feugiat nibh sed pulvinar proin gravida. Faucibus a pellentesque sit amet porttitor eget dolor morbi. Quam vulputate dignissim suspendisse in est. Faucibus interdum posuere lorem ipsum dolor. Proin libero nunc consequat interdum varius sit. Faucibus scelerisque eleifend donec pretium vulputate sapien. Dui faucibus in ornare quam viverra orci. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor magna.

                Aliquam sem et tortor consequat id porta nibh venenatis cras. Nascetur ridiculus mus mauris vitae ultricies leo integer. Auctor neque vitae tempus quam pellentesque nec nam aliquam sem. Et molestie ac feugiat sed lectus vestibulum mattis. Morbi tristique senectus et netus et malesuada fames ac. Dui nunc mattis enim ut. In cursus turpis massa tincidunt dui ut ornare lectus sit. Dignissim enim sit amet venenatis urna cursus eget. Risus ultricies tristique nulla aliquet enim. A scelerisque purus semper eget. Fusce ut placerat orci nulla pellentesque dignissim. Pellentesque nec nam aliquam sem et tortor consequat. Semper quis lectus nulla at volutpat diam. Neque laoreet suspendisse interdum consectetur libero id faucibus. Semper eget duis at tellus at urna condimentum mattis pellentesque. Imperdiet sed euismod nisi porta. Placerat orci nulla pellentesque dignissim enim sit. Suscipit adipiscing bibendum est ultricies integer quis auctor elit sed. Cras ornare arcu dui vivamus.

                Nibh cras pulvinar mattis nunc sed blandit libero volutpat. Arcu vitae elementum curabitur vitae nunc sed velit dignissim. Platea dictumst vestibulum rhoncus est. Posuere morbi leo urna molestie at. Eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis. Pretium nibh ipsum consequat nisl vel pretium lectus quam id. Nisi scelerisque eu ultrices vitae auctor eu. Velit sed ullamcorper morbi tincidunt. Vulputate mi sit amet mauris commodo quis imperdiet. Cras fermentum odio eu feugiat. Faucibus pulvinar elementum integer enim neque volutpat ac. Imperdiet nulla malesuada pellentesque elit eget gravida cum. Et pharetra pharetra massa massa ultricies mi quis hendrerit dolor. Maecenas ultricies mi eget mauris. Enim diam vulputate ut pharetra sit amet aliquam. Non sodales neque sodales ut. Adipiscing elit ut aliquam purus. Cursus sit amet dictum sit amet justo donec enim. Duis at consectetur lorem donec massa sapien faucibus et.

                Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget. Duis ut diam quam nulla. Tincidunt eget nullam non nisi est. Augue ut lectus arcu bibendum at varius. Varius sit amet mattis vulputate. Lorem ipsum dolor sit amet consectetur. Ac ut consequat semper viverra nam libero justo laoreet sit. Et netus et malesuada fames ac turpis egestas integer. Sagittis aliquam malesuada bibendum arcu vitae. Nisi est sit amet facilisis magna etiam tempor orci eu. Volutpat odio facilisis mauris sit amet massa vitae tortor condimentum. Enim ut tellus elementum sagittis vitae. Lorem mollis aliquam ut porttitor leo a.

                Sed libero enim sed faucibus turpis. Blandit aliquam etiam erat velit scelerisque in. Vel turpis nunc eget lorem dolor. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Tempus urna et pharetra pharetra. Mus mauris vitae ultricies leo integer malesuada nunc. Maecenas sed enim ut sem viverra aliquet. Nibh nisl condimentum id venenatis a condimentum vitae. Et ultrices neque ornare aenean euismod elementum nisi quis eleifend. Ornare lectus sit amet est placerat in egestas. Eu volutpat odio facilisis mauris sit. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit. Ac tincidunt vitae semper quis lectus nulla at volutpat. Felis eget velit aliquet sagittis id consectetur purus ut. Tristique risus nec feugiat in fermentum posuere urna. Enim neque volutpat ac tincidunt vitae. Vitae tortor condimentum lacinia quis vel eros donec ac. Aliquam sem et tortor consequat. Purus viverra accumsan in nisl nisi scelerisque eu.

                In fermentum et sollicitudin ac orci phasellus egestas. Justo eget magna fermentum iaculis. Massa vitae tortor condimentum lacinia. Enim blandit volutpat maecenas volutpat blandit. Aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. In massa tempor nec feugiat. Amet purus gravida quis blandit turpis cursus in hac habitasse. Amet nisl purus in mollis nunc sed id semper. Lacus sed turpis tincidunt id aliquet risus feugiat in ante. Non pulvinar neque laoreet suspendisse interdum consectetur libero id faucibus. Elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Netus et malesuada fames ac turpis egestas integer eget aliquet. Vel risus commodo viverra maecenas accumsan lacus vel facilisis. Tempus iaculis urna id volutpat lacus laoreet non curabitur gravida. Velit dignissim sodales ut eu sem integer vitae justo. Commodo elit at imperdiet dui. Lacus luctus accumsan tortor posuere.

                Aenean sed adipiscing diam donec adipiscing tristique risus. Tellus rutrum tellus pellentesque eu tincidunt tortor. Massa placerat duis ultricies lacus. Hendrerit dolor magna eget est lorem ipsum. Aliquet lectus proin nibh nisl condimentum id venenatis a. Sed elementum tempus egestas sed sed risus. Faucibus interdum posuere lorem ipsum dolor. Nisi quis eleifend quam adipiscing vitae proin sagittis nisl. Imperdiet sed euismod nisi porta lorem. Cras tincidunt lobortis feugiat vivamus at augue eget.
            </p>
        </div>
    );
}


export default Body;
